name: Sean Flinn
favicon: null
layout_spectrum: 0.8141021621413529
typography_spectrum: 0.12613464216701686
title: Sean Flinn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#333333'
    - '#939393'
    - '#626262'
    - '#b9b9b9'
  brandStrength: 0.3325506844557822
  lightness: 0.9120819391682744
  saturation: 0.8732830788940191
  rhythmicContrast: 0.4128265236504376
purpose: []
