name: Sean Flinn
favicon: null
layout_spectrum: 0.8141021621413529
typography_spectrum: 0.12613464216701686
title: Sean Flinn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfdf5'
    - '#141510'
    - '#7b624d'
    - '#9a9f9c'
    - '#baccd4'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.8732830788940191
  rhythmicContrast: 0.25
purpose: []
