name: Sean Flinn
favicon: null
layout_spectrum: 0.83363
typography_spectrum: 0.50676
title: Sean Flinn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c150f'
    - '#988e96'
    - '#47352f'
    - '#e2dde4'
    - '#77635d'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
